Server:
  port: "9001"
  # release / debug / test
  mode: "release"

MySQL:
  host: w8t-mysql
  port: 3306
  username: root
  password: w8t.123
  database: vingo
  timeout: 10s

Redis:
  host: w8t-redis
  port: 6379
  password: ""
  database: 0

Jwt:
  # 失效时间
  expire: 18000
